/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type EducationalSystem = { 'ib' : null } |
  { 'stateBoard' : null } |
  { 'other' : null } |
  { 'cbse' : null } |
  { 'icse' : null } |
  { 'igcse' : null };
export type Grade = { 'grade1' : null } |
  { 'grade2' : null } |
  { 'grade3' : null } |
  { 'grade4' : null } |
  { 'grade5' : null } |
  { 'grade6' : null } |
  { 'grade7' : null } |
  { 'grade8' : null } |
  { 'grade9' : null } |
  { 'grade10' : null } |
  { 'grade11' : null } |
  { 'grade12' : null };
export type Stream = { 'humanities' : null } |
  { 'commerce' : null } |
  { 'science' : null };
export type Time = bigint;
export interface UserProfile {
  'stream' : [] | [Stream],
  'educationalSystem' : EducationalSystem,
  'grade' : Grade,
  'timestamp' : Time,
}
export interface _SERVICE {
  'createUserProfile' : ActorMethod<
    [Grade, EducationalSystem, [] | [Stream]],
    undefined
  >,
  'getAllUserProfilesByTimestamp' : ActorMethod<[], Array<UserProfile>>,
  'getUserProfile' : ActorMethod<[], UserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];