/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Grade = IDL.Variant({
  'grade1' : IDL.Null,
  'grade2' : IDL.Null,
  'grade3' : IDL.Null,
  'grade4' : IDL.Null,
  'grade5' : IDL.Null,
  'grade6' : IDL.Null,
  'grade7' : IDL.Null,
  'grade8' : IDL.Null,
  'grade9' : IDL.Null,
  'grade10' : IDL.Null,
  'grade11' : IDL.Null,
  'grade12' : IDL.Null,
});
export const EducationalSystem = IDL.Variant({
  'ib' : IDL.Null,
  'stateBoard' : IDL.Null,
  'other' : IDL.Null,
  'cbse' : IDL.Null,
  'icse' : IDL.Null,
  'igcse' : IDL.Null,
});
export const Stream = IDL.Variant({
  'humanities' : IDL.Null,
  'commerce' : IDL.Null,
  'science' : IDL.Null,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'stream' : IDL.Opt(Stream),
  'educationalSystem' : EducationalSystem,
  'grade' : Grade,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'createUserProfile' : IDL.Func(
      [Grade, EducationalSystem, IDL.Opt(Stream)],
      [],
      [],
    ),
  'getAllUserProfilesByTimestamp' : IDL.Func(
      [],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Grade = IDL.Variant({
    'grade1' : IDL.Null,
    'grade2' : IDL.Null,
    'grade3' : IDL.Null,
    'grade4' : IDL.Null,
    'grade5' : IDL.Null,
    'grade6' : IDL.Null,
    'grade7' : IDL.Null,
    'grade8' : IDL.Null,
    'grade9' : IDL.Null,
    'grade10' : IDL.Null,
    'grade11' : IDL.Null,
    'grade12' : IDL.Null,
  });
  const EducationalSystem = IDL.Variant({
    'ib' : IDL.Null,
    'stateBoard' : IDL.Null,
    'other' : IDL.Null,
    'cbse' : IDL.Null,
    'icse' : IDL.Null,
    'igcse' : IDL.Null,
  });
  const Stream = IDL.Variant({
    'humanities' : IDL.Null,
    'commerce' : IDL.Null,
    'science' : IDL.Null,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'stream' : IDL.Opt(Stream),
    'educationalSystem' : EducationalSystem,
    'grade' : Grade,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'createUserProfile' : IDL.Func(
        [Grade, EducationalSystem, IDL.Opt(Stream)],
        [],
        [],
      ),
    'getAllUserProfilesByTimestamp' : IDL.Func(
        [],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [UserProfile], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };