/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface UserProfile {
    stream?: Stream;
    educationalSystem: EducationalSystem;
    grade: Grade;
    timestamp: Time;
}
export enum EducationalSystem {
    ib = "ib",
    stateBoard = "stateBoard",
    other = "other",
    cbse = "cbse",
    icse = "icse",
    igcse = "igcse"
}
export enum Grade {
    grade1 = "grade1",
    grade2 = "grade2",
    grade3 = "grade3",
    grade4 = "grade4",
    grade5 = "grade5",
    grade6 = "grade6",
    grade7 = "grade7",
    grade8 = "grade8",
    grade9 = "grade9",
    grade10 = "grade10",
    grade11 = "grade11",
    grade12 = "grade12"
}
export enum Stream {
    humanities = "humanities",
    commerce = "commerce",
    science = "science"
}
export interface backendInterface {
    createUserProfile(grade: Grade, educationalSystem: EducationalSystem, stream: Stream | null): Promise<void>;
    getAllUserProfilesByTimestamp(): Promise<Array<UserProfile>>;
    getUserProfile(): Promise<UserProfile>;
}
import type { EducationalSystem as _EducationalSystem, Grade as _Grade, Stream as _Stream, Time as _Time, UserProfile as _UserProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createUserProfile(arg0: Grade, arg1: EducationalSystem, arg2: Stream | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createUserProfile(to_candid_Grade_n1(this._uploadFile, this._downloadFile, arg0), to_candid_EducationalSystem_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUserProfile(to_candid_Grade_n1(this._uploadFile, this._downloadFile, arg0), to_candid_EducationalSystem_n3(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async getAllUserProfilesByTimestamp(): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUserProfilesByTimestamp();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUserProfilesByTimestamp();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile();
                return from_candid_UserProfile_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile();
            return from_candid_UserProfile_n9(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_EducationalSystem_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EducationalSystem): EducationalSystem {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Grade_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Grade): Grade {
    return from_candid_variant_n17(_uploadFile, _downloadFile, value);
}
function from_candid_Stream_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Stream): Stream {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Stream]): Stream | null {
    return value.length === 0 ? null : from_candid_Stream_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    stream: [] | [_Stream];
    educationalSystem: _EducationalSystem;
    grade: _Grade;
    timestamp: _Time;
}): {
    stream?: Stream;
    educationalSystem: EducationalSystem;
    grade: Grade;
    timestamp: Time;
} {
    return {
        stream: record_opt_to_undefined(from_candid_opt_n11(_uploadFile, _downloadFile, value.stream)),
        educationalSystem: from_candid_EducationalSystem_n14(_uploadFile, _downloadFile, value.educationalSystem),
        grade: from_candid_Grade_n16(_uploadFile, _downloadFile, value.grade),
        timestamp: value.timestamp
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    humanities: null;
} | {
    commerce: null;
} | {
    science: null;
}): Stream {
    return "humanities" in value ? Stream.humanities : "commerce" in value ? Stream.commerce : "science" in value ? Stream.science : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ib: null;
} | {
    stateBoard: null;
} | {
    other: null;
} | {
    cbse: null;
} | {
    icse: null;
} | {
    igcse: null;
}): EducationalSystem {
    return "ib" in value ? EducationalSystem.ib : "stateBoard" in value ? EducationalSystem.stateBoard : "other" in value ? EducationalSystem.other : "cbse" in value ? EducationalSystem.cbse : "icse" in value ? EducationalSystem.icse : "igcse" in value ? EducationalSystem.igcse : value;
}
function from_candid_variant_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    grade1: null;
} | {
    grade2: null;
} | {
    grade3: null;
} | {
    grade4: null;
} | {
    grade5: null;
} | {
    grade6: null;
} | {
    grade7: null;
} | {
    grade8: null;
} | {
    grade9: null;
} | {
    grade10: null;
} | {
    grade11: null;
} | {
    grade12: null;
}): Grade {
    return "grade1" in value ? Grade.grade1 : "grade2" in value ? Grade.grade2 : "grade3" in value ? Grade.grade3 : "grade4" in value ? Grade.grade4 : "grade5" in value ? Grade.grade5 : "grade6" in value ? Grade.grade6 : "grade7" in value ? Grade.grade7 : "grade8" in value ? Grade.grade8 : "grade9" in value ? Grade.grade9 : "grade10" in value ? Grade.grade10 : "grade11" in value ? Grade.grade11 : "grade12" in value ? Grade.grade12 : value;
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n9(_uploadFile, _downloadFile, x));
}
function to_candid_EducationalSystem_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationalSystem): _EducationalSystem {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_Grade_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Grade): _Grade {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_Stream_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): _Stream {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream | null): [] | [_Stream] {
    return value === null ? candid_none() : candid_some(to_candid_Stream_n6(_uploadFile, _downloadFile, value));
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Grade): {
    grade1: null;
} | {
    grade2: null;
} | {
    grade3: null;
} | {
    grade4: null;
} | {
    grade5: null;
} | {
    grade6: null;
} | {
    grade7: null;
} | {
    grade8: null;
} | {
    grade9: null;
} | {
    grade10: null;
} | {
    grade11: null;
} | {
    grade12: null;
} {
    return value == Grade.grade1 ? {
        grade1: null
    } : value == Grade.grade2 ? {
        grade2: null
    } : value == Grade.grade3 ? {
        grade3: null
    } : value == Grade.grade4 ? {
        grade4: null
    } : value == Grade.grade5 ? {
        grade5: null
    } : value == Grade.grade6 ? {
        grade6: null
    } : value == Grade.grade7 ? {
        grade7: null
    } : value == Grade.grade8 ? {
        grade8: null
    } : value == Grade.grade9 ? {
        grade9: null
    } : value == Grade.grade10 ? {
        grade10: null
    } : value == Grade.grade11 ? {
        grade11: null
    } : value == Grade.grade12 ? {
        grade12: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EducationalSystem): {
    ib: null;
} | {
    stateBoard: null;
} | {
    other: null;
} | {
    cbse: null;
} | {
    icse: null;
} | {
    igcse: null;
} {
    return value == EducationalSystem.ib ? {
        ib: null
    } : value == EducationalSystem.stateBoard ? {
        stateBoard: null
    } : value == EducationalSystem.other ? {
        other: null
    } : value == EducationalSystem.cbse ? {
        cbse: null
    } : value == EducationalSystem.icse ? {
        icse: null
    } : value == EducationalSystem.igcse ? {
        igcse: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Stream): {
    humanities: null;
} | {
    commerce: null;
} | {
    science: null;
} {
    return value == Stream.humanities ? {
        humanities: null
    } : value == Stream.commerce ? {
        commerce: null
    } : value == Stream.science ? {
        science: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
